name: Publish to DockerHub

on:
  push:
    branches:
      - main

jobs:
  publish-extension:
    name: Build extension and Push image to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        env:
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/react-extension
          TAG: 0.0.0-${{github.run_number}}

        run: make push-extension
